version: '3.8'
services:
  postgresdb:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=felanmalan
      - POSTGRES_DB=felanmalan
    volumes:
      - ./data:/var/lib/postgresql/data
  server:
    build: ./packages/server
    ports:
      - 4000:4000
