version: "3.7"

# The two servers, aptly named "server" and "slussen" are both set to restart
# until success. This is so that they keep trying to run their migrations until
# the two Postgres instances are ready

services:
  felanmalan-postgres:
    image: postgres:12.2-alpine
    ports:
      # Note: Within the docker-compose network the server is reachable on port 5432
      - 5442:5432
    environment:
      - POSTGRES_INITDB_ARGS=--encoding=utf8
      - TZ=Europe/Stockholm
      - POSTGRES_USER=iteamadmin
      - POSTGRES_DB=felanmalan
      - POSTGRES_PASSWORD=adminadmin1337
    volumes:
      - db-felanmalan:/var/lib/postgresql/data
    networks:
      - felanmalan

  server:
    build: ./packages/server
    environment:
      - DATABASE_URL=postgres://iteamadmin:adminadmin1337@felanmalan-postgres/felanmalan
    volumes:
      - ./packages/server:/app
    ports:
      - 3001:3001
    networks:
      - felanmalan
      - services
    restart: on-failure
    depends_on:
      - felanmalan-postgres

  client:
    build: ./packages/client
    volumes:
      - ./packages/client:/app
    ports:
      - 3000:3000
    networks:
      - felanmalan

  slussen:
    image: docker.pkg.github.com/allmannyttan/slussen/slussen:latest
    ports:
      - 4000:4000
    networks:
      - slussen
      - services
    environment:
      - "PORT=${PORT:-4000}"
      - "FAST_API__BASE_URL=${FASTAPIBASEURL:-http://www.fastapi.se/backendprop/v1_WP/api/}"
      - "FAST_API__ACCESS_TOKEN=${FASTAPIACCESSTOKEN:-12345}"
      - "FAST_API__USER=${FASTAPIUSER:-demouser}"
      - "FAST_API__PASSWORD=${FASTAPIPASSWORD:-demopassword}"
      - "DATABASE_URL=${DATABASE_URL:-postgres://postgres:postgrespassword@slussen-postgres:5432/api-db}"
      - "POSTGRES__HOST=${POSTGRESHOST:-slussen-postgres}"
    restart: on-failure
    depends_on:
      - slussen-postgres

  slussen-postgres:
    image: postgres:12.2-alpine
    networks:
      - slussen
    environment:
      TZ: Europe/Stockholm
      POSTGRES_DB: api-db
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
networks:
  felanmalan:
  slussen:
  services:

volumes:
  db-data:
    driver: local
  db-felanmalan:
    driver: local
